# Generated by Django 5.2.1 on 2025-05-09 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=35, unique=True)),
                ('email', models.EmailField(blank=True, max_length=35, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('fiverr', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('git', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('linkedin', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('upwork', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('x', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('youtube', models.CharField(blank=True, max_length=35, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ('-last_modified',),
            },
        ),
    ]
