# Generated by Django 5.2.1 on 2025-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_git_portfolio_x_portfolio_youtube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facebook',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
